Косенко Юлия. Task 07
MeganDorian/formal-lang-course pull request #6
Opened 2023-04-09 19:47 UTC by MeganDorian

- [X] Реализован тип для представления рекурсивных конечных автоматов.
- [X] Реализован внутреннее представление для ECFG.
- [X] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html), реализована **функцию** преобразования контекстно-свободной грамматики в стандартном формате pyformlang в ECFG.
- [X] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html), [регулярными выражениями](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression) и [конечными автоматами](https://pyformlang.readthedocs.io/en/latest/usage.html#finite-automata), реализована **функцию** преобразования контекстно-свободной грамматики в ECFG в рекурсивный конечный автомат.
- [X] Реализована **функцию** минимизации рекурсивного конечного автомата.
- [X] Добавлены необходимые тесты.

2023-04-10 08:59 UTC, rustam-azimov requested changes

2023-04-10 08:59 UTC, rustam-azimov commented on project/task07/rsm.py
> +class RSM:
Добавьте также возможность возвращать матрицы смежности

2023-04-10 08:59 UTC, rustam-azimov commented on project/task07/ecfg.py
> +    def from_file(self, filename: str):
Добавьте также возможность построения из строки

2023-04-13 21:51 UTC, MeganDorian commented on project/task07/rsm.py
> +class RSM:
добавила

2023-04-13 21:51 UTC, MeganDorian commented on project/task07/ecfg.py
> +    def from_file(self, filename: str):
добавила

2023-04-16 07:47 UTC, rustam-azimov approved these changes

2023-04-16 23:55 UTC, merged