Косенко Юлия. Task 08
MeganDorian/formal-lang-course pull request #7
Opened 2023-04-16 13:09 UTC by MeganDorian

- [x] Реализовать **функцию**, основанную на алгоритме Хеллингса, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
  - Результат работы функции --- множество троек вида (вершина, нетерминал, вершина).
  - Предусмотрите возможность получать граф из различных источников в различных форматах.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Для преобразования грамматики в ОНФХ использовать результаты предыдущих работ.
- [x] На основе предыдущей функции реализовать функцию, позволяющую решать задачу достижимости для заданного набора стартовых и финальных вершин, и заданного нетерминала.
- [x] Добавить необходимые тесты.

2023-04-18 09:40 UTC, rustam-azimov requested changes

2023-04-18 09:40 UTC, rustam-azimov commented on project/task08/hellings.py
> +def hellings_algorithm(graph, cfg: CFG):
предусмотрите тут разные форматы для графа и грамматики, например из файла

2023-04-18 12:28 UTC, MeganDorian commented on project/task08/hellings.py
> +def hellings_algorithm(graph, cfg: CFG):
я попутала и сделала это в `get_reachable_by_hellings` функции :(

2023-04-18 12:36 UTC, MeganDorian commented on project/task08/hellings.py
> +def hellings_algorithm(graph, cfg: CFG):
граф можно считывать из файла
грамматику можно считывать из файла или формировать из текста

2023-04-18 12:37 UTC, MeganDorian commented on project/task08/hellings.py
> +def hellings_algorithm(graph, cfg: CFG):
вынесла это из `get_reachable_by_hellings` в `hellings_algorithm`

2023-04-18 13:21 UTC, MeganDorian commented
короче я немного сделала в итоге с затравкой на 9ую домашку, вынесла логику алгоритма в отдельный класс, в котором граф и грамматика принимается в описанных выше видах

2023-04-24 10:42 UTC, rustam-azimov approved these changes

2023-04-24 14:10 UTC, merged